# Import time module
import time
####################### START CODE TO CHECK RUNTIME FOR ##################################    
def underscorifySubstring(string, substring):
    #Name: Underscorify Substring
	#Category and difficulty: Strings, Hard
    #time: TBD
	#space: Max O(n) where n is the length of string

    #Edge case
    if(substring == ""):
        return "_" + string + "_"
        
    ssLength = len(substring)
    current = 0

    while(current < len(string)):
        #CASE - substring found
        if(string[current:current+ssLength] == substring):
            start = current
            end = findend(string, substring, start)
            string = string[:start] + "_" + string[start:end] + "_" + string[end:]
            current = end+1
        #CASE - substring not found
        else:
            current += 1
            
    return string

def findend(string, substring, startPoint):
    ssLength = len(substring)
    endPoint = startPoint + ssLength

    #This is also an edge case
    if(ssLength == 1):
        current = startPoint+1
        while(current < len(string) and string[current] == substring[0]):
            current += 1
        return current
        
    anchor = startPoint+1
    current = anchor
    while(endPoint < len(string) and current <= endPoint):
        if(string[current : current + ssLength] == substring):
            endPoint = current + ssLength
        current += 1
    return endPoint


####################### END CODE TO CHECK RUNTIME FOR ##################################    
# record start time
start = time.time()

substring1 = "a"
substring2 = "ab"
substring3 = "abc"
mainstring = "abababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaaabababababababababababababaababaaabbababaa"
# Copy code to check runtime for
print(underscorifySubstring(mainstring, substring1))
# Mark end time of code
end = time.time()
 
# print the difference between start
# and end time in milli. secs
print("The time of execution of above program 1 is :",
      (end-start) * 10**3, "ms")

start = time.time()
 
# Copy code to check runtime for
print(underscorifySubstring(mainstring, substring2))
# Mark end time of code
end = time.time()
 
# print the difference between start
# and end time in milli. secs
print("The time of execution of above program 2 is :",
      (end-start) * 10**3, "ms")

start = time.time()
 
# Copy code to check runtime for
print(underscorifySubstring(mainstring, substring3))
# Mark end time of code
end = time.time()
 
# print the difference between start
# and end time in milli. secs
print("The time of execution of above program 3 is :",
      (end-start) * 10**3, "ms")
